on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
          extraPullNames: nixpkgs-python
      - run: nix profile install nixpkgs#devenv
      - uses: actions/checkout@v6
      - run: devenv shell -- npm ci
      - run: devenv test
